import { Divider } from '@nextui-org/react';
import Head from 'next/head';
import styled from 'styled-components';

import 'katex/dist/katex.min.css';

const CvItemTitle = styled.p`
  font-weight: 500;
  margin: 0;
`;

const CvSectionTitle = styled.h2`
  font-weight: 500;
  font-size: 1.1rem;
  text-align: center;
`;

const CvItemSubTitle = styled.p`
  font-weight: regular;
  margin: 0;
  font-style: italic;
`;

const CvItemRegular = styled.p`
  font-weight: 400;
  margin: 0;
`;

const CvItemLighter = styled.p`
  font-weight: light;
  margin: 0;
  font-style: italic;
`;

const CvSpaceBetween = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin: 0.2em 0em;
`;

const IndentUL = styled.ul`
  margin: 0.3em 0em;
`;

const CvLiItem = styled.li`
  font-weight: 300;
  font-size: 0.95rem;
  line-height: 150%;
  margin: 0.2em 0em;
`;

const ResItem = ({
  children,
  mainleft,
  mainright,
  subtextleft,
  subtextright,
}) => (
  <div
    style={{
      margin: '1em 0em',
    }}
  >
    <CvSpaceBetween>
      <CvItemTitle>{mainleft}</CvItemTitle>
      <CvItemLighter>{mainright}</CvItemLighter>
    </CvSpaceBetween>
    <CvSpaceBetween>
      <CvItemSubTitle>{subtextleft}</CvItemSubTitle>
      <CvItemLighter>{subtextright}</CvItemLighter>
    </CvSpaceBetween>

    <div style={{ padding: '.2em .3em' }}>{children}</div>
  </div>
);

export default function CV() {
  return (
    <>
      <Head>
        <title>CV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/websiteicon.ico" />
      </Head>

      {/* <h2>CV</h2>

      <p>
        An up-to-date copy of my CV is available upon request. Please feel free
        to contact me with any questions.
      </p> */}
      <CvSectionTitle>Education</CvSectionTitle>

      <ResItem
        mainleft={'Carnegie Mellon University'}
        mainright={'2023 - Present'}
        subtextleft={'B.S. in Computer Science'}
        subtextright={'Pittsburgh, PA'}
      >
        {/* <CvItemRegular>Selected Coursework:</CvItemRegular>
        <IndentUL>
          <CvLiItem>
            15-151 Mathematical Foundations for Computer Science
          </CvLiItem>
          <CvLiItem>21-241 Matrices and Linear Transformations</CvLiItem>
          <CvLiItem>15-122 Principles of Imperative Computation</CvLiItem>
          <CvLiItem>85-219 Foundations of Brain & Behavior</CvLiItem>
        </IndentUL> */}
      </ResItem>
      <Divider></Divider>
      <ResItem
        mainleft={'Worcester Polytechnic Institute'}
        mainright={'2022 - 2023'}
        subtextleft={'Dual Enrollment'}
        subtextright={'Worcester, MA'}
      >
        <CvItemRegular>Coursework:</CvItemRegular>
        <IndentUL>
          <CvLiItem>
            CS 4801: Introduction to Cryptography and Communication Security
          </CvLiItem>
          <CvLiItem>CS 2303: Systems Programming Concepts</CvLiItem>
          <CvLiItem>
            CS 2103: Accelerated Object-Oriented Design Concepts
          </CvLiItem>
          <CvLiItem>CS 2022: Discrete Mathematics</CvLiItem>
          <CvLiItem>MA 464X: Introduction to Time Series Analysis</CvLiItem>
          <CvLiItem>MA 3823: Group Theory</CvLiItem>
          <CvLiItem>MA 3831: Principles of Real Analysis I</CvLiItem>
          <CvLiItem>MA 3832: Principles of Real Analysis II</CvLiItem>
          <CvLiItem>MA 2071: Matrices and Linear Algebra I</CvLiItem>
          <CvLiItem>MA 1024: Calculus IV </CvLiItem>
          <CvLiItem>MA 1023: Calculus III</CvLiItem>
          <CvLiItem>SP 3521: Advanced Spanish I</CvLiItem>
          <CvLiItem>EN 1251: Introduction to Literature</CvLiItem>
          <CvLiItem>HI 2350: Topics in the History of Science</CvLiItem>
          <CvLiItem>
            EN 2281: World Literatures: Best of Russian Literature
          </CvLiItem>
        </IndentUL>
      </ResItem>
      <Divider></Divider>
      <CvSectionTitle>Publications</CvSectionTitle>
      <IndentUL>
        <CvLiItem>
          S. Servan-Schreiber, S. Beyzerov, E. Yablon and H. Park, &quot;Private
          Access Control for Function Secret Sharing,&quot; in 2023 IEEE
          Symposium on Security and Privacy (SP), San Francisco, CA, US, 2023
          pp. 809-828. doi: 10.1109/SP46215.2023.00072
        </CvLiItem>
      </IndentUL>
    </>
  );
}
