import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components';

export default function Home() {
  return (
    <>
      <Head>
        <title>Simon Beyzerov</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/websiteicon.ico" />
      </Head>
      <div>
        <p>
          Hi! I&apos;m Simon, a senior at the Massachusetts Academy of Math and Science at WPI.
          I am broadly interested in mathematics and computer science, with my primary 
          research interests lying in theoretical computer science and cryptography. 
          See my projects for a more detailed description of my work.
        </p>
        <p>
          
        </p>
      </div>
    </>
  )
}
