import Head from 'next/head';
import styled from 'styled-components';

import {
  Badge,
  Collapse,
  Grid,
  Spacer,
  Text,
  Tooltip,
} from '@nextui-org/react';
import { Award } from '/components/icons/index';

import stylesProject from '../styles/Projects.module.css';

import { useAnimation } from 'framer-motion';
import { Fragment, useEffect } from 'react';
import { useInView } from 'react-intersection-observer';

import 'katex/dist/katex.min.css';
import Latex from 'react-latex-next';

const LinkButton = styled.a`
  /* color: var(--main-blue);
    text-decoration: none;

    &:hover {
      color: var(--hover-blue);
    } */
`;

const ColH2 = styled.h2`
  /* margin-bottom: 0; */
`;

const NoteItem = ({ children, title, mainIcon }) => (
  <>
    <Tooltip
      content={children}
      color="primary"
      style={{ paddingLeft: '.3rem' }}
    >
      <div className="svgContainer">{mainIcon}</div>
    </Tooltip>
  </>
);

const ProjectTag = ({ children, tags }) => (
  <>
    <Grid.Container gap={0.5}>
      {tags.map((item, index) => (
        <Grid>
          <Badge disableOutline isSquared variant={'flat'}>
            {item}
          </Badge>
        </Grid>
      ))}
    </Grid.Container>
  </>
);

const ProjectTitle = ({ children, notes }) => (
  <div className={stylesProject.hFlex}>
    <Text className={stylesProject.projectTitle}>{children}</Text>
    <div
      className="noteContainer"
      style={{ flex: '1', display: 'inline-block' }}
    >
      {notes.map((item, index) => (
        <NoteItem
          key={item.title + index}
          mainIcon={item.displayIcon}
          title={item.title}
        >
          {item.description}
        </NoteItem>
      ))}
    </div>
  </div>
);

const ProjectItem = ({ title, children, notes = [] }) => (
  <div className={stylesProject.projectItem}>
    <ProjectTitle key={title} notes={notes}>
      {title}
    </ProjectTitle>
    {children}
  </div>
);

const ProjectItemCollapse = ({ title, children, notes, links }) => {
  const control = useAnimation();
  const [ref, inView] = useInView();

  useEffect(() => {
    if (inView) {
      control.start('visible');
    } else {
      control.start('hidden');
    }
  }, [control, inView]);

  return (
    <Collapse
      css={{ padding: 0 }}
      a
      // arrowIcon={<MdKeyboardArrowRight/>}
      title={
        <ProjectItem key={title} title={title} notes={notes}></ProjectItem>
      }
      // shadow={true}
      // bordered={true}
    >
      <div>{children}</div>

      <div className={stylesProject.hFlex} style={{ paddingTop: '0.2em' }}>
        {links.map((item, index) => (
          <Fragment key={item.title + toString(index)}>
            {/* <button class="button-28" role="button">{item.title}</button> */}
            <span>
              [
              {
                <LinkButton target="_blank" rel="noreferrer" href={item.url}>
                  {item.title}
                </LinkButton>
              }
              ]
            </span>
            {/* <Link  rel="noreferrer" target="_blank"> */}
            {/* <Button style={{height: '1.4rem', marginTop: ".4rem", fontSize: "0.8rem"}}
               auto
              >
                
            </Button> */}
            {/* </Link> */}
            <Spacer x={0.5} />
          </Fragment>
        ))}
      </div>
    </Collapse>
  );
};

export default function Projects() {
  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/websiteicon.ico" />
      </Head>
      <div>
        <ColH2>Cryptography</ColH2>
        <Grid.Container css={{ paddingLeft: '0.5rem' }}>
          <Grid>
            <Collapse.Group css={{ padding: 0 }}>
              <ProjectItemCollapse
                title="Private Access Control for Function Secret Sharing"
                links={[
                  {
                    title: 'Paper (full version)',
                    url: 'https://eprint.iacr.org/2022/1707',
                  },
                  {
                    title: 'Paper (conference version)',
                    url: 'https://www.computer.org/csdl/proceedings-article/sp/2023/933600b257/1Js0DNr8h6U',
                  },
                  {
                    title: 'Slides',
                    url: 'https://sachaservanschreiber.com/slides/pacls.pdf',
                  },
                  {
                    title: 'Code',
                    url: 'https://github.com/sachaservan/pacl',
                  },
                ]}
                notes={[
                  {
                    displayIcon: <Award />,
                    title: '',
                    description:
                      'Awarded Bronze Medal at S.T.-Yau North America',
                  },
                ]}
              >
                <h3>Authors</h3>

                <p>
                  Sacha Servan-Schreiber, <u>Simon Beyzerov</u>, Eli Yablon,
                  Hyojae Park
                </p>

                <h3>Publications/Talks</h3>
                <p>
                  <em>
                    IEEE Symposium on Security and Privacy (Oakland) 2023 ,
                    AMS-PME at the Joint Mathematics Meeting (JMM 2023)
                  </em>
                </p>

                <h3>About</h3>

                <p>
                  <Latex>
                    In function secret sharing (FSS) a dealer can privately
                    outsource some function $f$ to a set of evaluators. These
                    evaluators can evaluate the function on some input $x$
                    without learning the result of the computation $f(x)$. We
                    introduce the notion of private access control for function
                    secret sharing, whereby we restrict the dealer to only be
                    able to secret-share a function that they have been granted
                    access to, all while maintaining privacy. Written in
                    conjunction with MIT PRIMES. Cryptography paper developing
                    distributed zero knowledge proof protocols towards access
                    control for secret-shared functions.
                  </Latex>
                </p>
              </ProjectItemCollapse>

              <ProjectItemCollapse
                title="Cloak: A Versatile Framework for Anonymous Authentication"
                links={[
                  {
                    title: 'Slides',
                    url: 'https://math.mit.edu/research/highschool/primes/materials/2021/October/8-4-Beyzerov-Yablon.pdf',
                  },
                ]}
              >
                <h3>Authors</h3>
                <p>
                  Sacha Servan-Schreiber, <u>Simon Beyzerov</u>, Eli Yablon
                </p>
                <h3>About</h3>
                <p>
                  <Latex>
                    Many online resources are pay-walled or otherwise restricted
                    to the public. To access these resources, users need to
                    prove access privileges through an authentication mechanism.
                    For example, news websites such as the New York Times (NYT)
                    offer news articles exclusively to paid subscribers. To
                    access NYT articles, users provide the NYT website with an
                    email and password associated with an active subscription
                    (users to the NYT). What if users want to preserve their
                    privacy and not reveal which articles they consume? An
                    anonymous authentication mechanism can solve this problem.
                    We introduce a novel zero-knowledge proof protocol towards
                    the development of a framework for anonymous authentication.
                    Written in conjunction with MIT PRIMES. Cryptography paper
                    developing privacy preserving authentication through
                    secret-shared zero-knowledge proof protocols.
                  </Latex>
                </p>
              </ProjectItemCollapse>

              <ProjectItemCollapse
                title="Authenticated Metadata-hiding Anonymous Communication"
                links={[
                  { title: 'Code', url: 'https://github.com/sim15/anon-com' },
                ]}
              >
                <h3>Authors</h3>
                <p>Simon Beyzerov</p>
                <h3>About</h3>
                <p>
                  <Latex>
                    Paired with the rise of consumer data analytics, the
                    continued transition of interpersonal communication onto the
                    Internet has made privacy an increasingly important
                    requirement in many network systems. Although attempts by
                    services such as WhatsApp, iMessage, and Facebook Messenger
                    to employ methods of end-to-end encryption have succeeded in
                    securing message content, leaked metadata has exposed the
                    power of underlying communication data. In this work, we
                    present a set of lightweight constructions for anonymous
                    communication with cryptographic privacy guarantees for
                    users. Independent research paper exploring how anonymous
                    authentication techniques can be used to improve the current
                    state of the art in anonymous communication systems with
                    cryptographic privacy guarantees.
                  </Latex>
                </p>
              </ProjectItemCollapse>

              <ProjectItemCollapse
                title="Authenticated Single-Server Private Aggregation"
                links={[]}
              >
                <h3>Authors</h3>
                <p>
                  Sacha Servan-Schreiber, Mayuri Sridhar, <u>Simon Beyzerov</u>
                </p>
                <h3>About</h3>
                <p>(Still in the works!)</p>
              </ProjectItemCollapse>

              <ProjectItemCollapse
                title="Seed-Homomorphic Pseudorandom Generators from Learning with Errors / Multi-Server Distributed Point Functions"
                links={[]}
              >
                <h3>Authors</h3>
                <h3>About</h3>
                <p>(Still in the works!)</p>
              </ProjectItemCollapse>

              <ProjectItemCollapse title="Moderately Hard Functions" links={[]}>
                <h3>Authors</h3>
                <h3>About</h3>
                <p>(Still in the works!)</p>
              </ProjectItemCollapse>
            </Collapse.Group>
          </Grid>
        </Grid.Container>
      </div>
      <div>
        <ColH2>Mathematics</ColH2>
        <Grid.Container css={{ paddingLeft: '0.5rem' }}>
          <Grid>
            <Collapse.Group
              //  splitted
              css={{ padding: 0 }}
            >
              <ProjectItemCollapse
                title="Autoregressive Conditional Heteroskedasticity Models of Volatility in Asset Pricing"
                notes={[]}
                links={[
                  { title: 'Paper', url: '/archpaper.pdf' },
                  { title: 'Slides', url: '/archtalk.pdf' },
                  {
                    title: 'R code',
                    url: 'https://github.com/sim15/arch_model',
                  },
                ]}
              >
                <ProjectTag
                  tags={[
                    'time series analysis',
                    'statistics',
                    'econometrics',
                    'R',
                    <Latex>$\LaTeX$</Latex>,
                  ]}
                />
                <h3>About</h3>
                <p>
                  Explorative paper on conditional heteroskedasticity in
                  financial market data and other applications. Discuss theory
                  of modeling autocorrelation within these systems through
                  specialized time series models (ARCH) and provide insight into
                  forecasting methodology. (Specifically within risk analysis
                  and volatility forecasting). Short talk given about
                  identifying such processes part of a smaller project at WPI.
                </p>
                <h3>Abstract</h3>
                <p>
                  In this paper, we explore the development, identification, and
                  motivations behind a fundamental class of time series models:
                  autoregressive conditional heteroskedasticity (ARCH) models.
                  First introduced by Robert Engle in his seminal work, ARCH
                  models have given way to a rich class of econometric inquiry.
                  Concerned with conditional-level fluctuations in variance,
                  this unique class of models allows us to analyze dependence in
                  residual series data. Finding particular applications within
                  financial time series, ARCH modeling has shown continued
                  success in risk analysis and volatility forecasting. They have
                  especially seen applications within asset pricing, where risk
                  is a central concern in making optimal financial decisions. We
                  examine these considerations and more while discussing the
                  motivations behind such models. By looking at the historical
                  returns of one asset in particular, we provide a demonstrative
                  analysis of the ARCH modeling process. We identify distinct
                  effects in our data that suggest an ARCH process and go on to
                  introduce a parsimonious model that fits our data well and
                  forecasts future volatility
                </p>
              </ProjectItemCollapse>
              <ProjectItemCollapse
                title="HiMCM 2023"
                notes={[
                  {
                    displayIcon: <Award />,
                    title: '',
                    description: 'Awarded Meritorious',
                  },
                ]}
                links={[{ title: 'Paper', url: '/HiMCM_12855.pdf' }]}
              >
                <ProjectTag
                  tags={[
                    'mathematical modeling',
                    'Python',
                    <Latex>$\LaTeX$</Latex>,
                  ]}
                />
                <h3>About</h3>
                <p>
                  Mathematical modeling paper written during the 2022-23 High
                  School Mathematical Contest in Modeling (HiMCM). Modeled the
                  causes and impact of colony collapse disorder on honeybee
                  populations.
                </p>
              </ProjectItemCollapse>
              <ProjectItemCollapse
                title="Finite Group Theory and the Classification of Finite Simple Groups"
                notes={[]}
                links={[
                  { title: 'Paper', url: '/finSimpleGroups.pdf' },
                  { title: 'Slides', url: '/finSimpleGroupsSlides.pdf' },
                ]}
              >
                <ProjectTag
                  tags={[
                    'number theory',
                    'finite group theory',
                    'abstract algebra',
                    <Latex>$\LaTeX$</Latex>,
                  ]}
                />
                <h3>About</h3>
                <p>
                  A short talk (and accompanying write-up) on the{' '}
                  <a
                    target="_blank"
                    rel="noreferrer"
                    href="https://en.wikipedia.org/wiki/Classification_of_finite_simple_groups"
                  >
                    classification
                  </a>{' '}
                  of finite{' '}
                  <a
                    target="_blank"
                    rel="noreferrer"
                    href="https://en.wikipedia.org/wiki/Simple_group"
                  >
                    simple groups
                  </a>
                  . Part of a smaller, two-week-long group theory project with
                  WPI undergrads.
                </p>
              </ProjectItemCollapse>
              <ProjectItemCollapse
                title="IMMC 2022"
                notes={[
                  {
                    displayIcon: <Award />,
                    title: '',
                    description: 'Awarded US Finalist',
                  },
                ]}
                links={[{ title: 'Paper', url: '/immc_paper.pdf' }]}
              >
                <ProjectTag
                  tags={[
                    'mathematical modeling',
                    'Python',
                    <Latex>$\LaTeX$</Latex>,
                  ]}
                />
                <h3>About</h3>
                <p>
                  Mathematical modeling paper written during a the 2022
                  International Mathematical Modeling Competition (IMMC).
                  Modeled planar loading and disembarking while optimizing both
                  processes in a diverse set of aircrafts.
                </p>
              </ProjectItemCollapse>
              <ProjectItemCollapse
                title="HiMCM 2021"
                notes={[
                  {
                    displayIcon: <Award />,
                    title: '',
                    description: 'Awarded Meritorious',
                  },
                ]}
                links={[]}
              >
                <ProjectTag
                  tags={[
                    'mathematical modeling',
                    'Python',
                    <Latex>$\LaTeX$</Latex>,
                  ]}
                />
                <h3>About</h3>
                <p>
                  Mathematical modeling paper written during the 2021-22 High
                  School Mathematical Contest in Modeling (HiMCM). Modeled the
                  causes, future outlook, and potential consequences of rapidly
                  depleting water levels at Lake Mead, Nevada, the nations
                  largest freshwater reservoir.
                </p>
              </ProjectItemCollapse>
              <ProjectItemCollapse
                title="MathWorks 2022"
                notes={[
                  {
                    displayIcon: <Award />,
                    title: '',
                    description:
                      'Advanced to Second Round of Competition (Top ~100 papers)',
                  },
                ]}
                links={[]}
              >
                <ProjectTag
                  tags={[
                    'mathematical modeling',
                    'Python',
                    <Latex>$\LaTeX$</Latex>,
                  ]}
                />
                <h3>About</h3>
                <p>
                  Mathematical modeling paper written during the 2022 MathWorks
                  Mathematical Modeling Competition. Modeled changes in
                  employment caused by a pandemic-induced virtual workplace.
                  Considered future outlook, causes, and conducted a broader
                  mathematical and social analysis.
                </p>
              </ProjectItemCollapse>
            </Collapse.Group>
          </Grid>
        </Grid.Container>
      </div>
      <div>
        <ColH2>Other</ColH2>
        <Grid.Container css={{ paddingLeft: '0.5rem' }}>
          <Grid>
            <Collapse.Group
              //  splitted
              css={{ padding: 0 }}
            >
              <ProjectItemCollapse
                title="SigmaML"
                links={[
                  { title: 'Slides', url: '/sigmaml_slides.pdf' },
                  { title: 'Github', url: 'https://github.com/sim15/sigmaml' },
                ]}
              >
                <ProjectTag
                  tags={['JavaScript', 'Svelte', 'Python', 'machine learning']}
                />
                <h3>About</h3>
                <p>
                  A cross-platform desktop application for building machine
                  learning models with TensorFlow, aggregating all steps of the
                  development process. Built with web-based technology:{' '}
                  <u>JavaScript, Svelte, Electron, Python</u>.
                </p>
              </ProjectItemCollapse>
              <ProjectItemCollapse
                title="Mealgo: Recipe Filtering"
                links={[
                  { title: 'Poster', url: '/a4g_mealgo_poster.pdf' },
                  { title: 'Github', url: 'https://github.com/sim15/Mealgo3' },
                ]}
              >
                <ProjectTag tags={['Java', 'Firebase']} />
                <h3>About</h3>
                <p>
                  Android application designed to provide intelligent meal and
                  recipe recommendation that considers both pricing and
                  individual user preferences. Developed with a tailored dataset
                  of over 500,000 recipes and thousands of unique ingredients,
                  all with their respective nutritional information. Developed
                  in <u>Kotlin</u> and database hosted on <u>Firebase</u>.
                </p>
              </ProjectItemCollapse>
              <ProjectItemCollapse
                title="NaVi: Aid for Independent Navigation for the Visually Impaired"
                links={[{ title: 'Poster', url: '/navi_poster.pdf' }]}
              >
                <ProjectTag tags={['engineering', 'C++']} />
                <h3>About</h3>
                <p>
                  Designed a physical aid for the independent navigation of
                  public spaces for those with visual impairments. Designed
                  software for automated guidance and designed a haptic device
                  to aid those attempting to navigate through unadapted
                  environments. Allows for independent parties to deploy
                  schematics that aid individuals in the respective space.
                </p>
              </ProjectItemCollapse>
            </Collapse.Group>
          </Grid>
        </Grid.Container>
      </div>

      {/* <div>
        <h2>Mass Academy Coursework</h2>
        <p className={stylesProject.projectSectionCaption}>
          For prospective Mass Academy students, alumni, or for anyone
          interested: past assignments and projects completed during the 2021-22
          school year are available upon request. Certain assignments will be
          available in the future.
        </p>
      </div> */}
    </>
  );
}
