import Head from 'next/head'
import Image from 'next/image'
import LazyShow from "/components/LazyShow";
import styled from 'styled-components';

import { Award, Svg100Award, Medal } from '/components/icons/index'
import { Tooltip, Button, Spacer, Collapse, Text, Grid, Link } from '@nextui-org/react';
import InsertDriveFileIcon from '@mui/icons-material/InsertDriveFile';

import stylesProject from '../styles/Projects.module.css';


import TreeView from '@mui/lab/TreeView';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import ChevronRightIcon from '@mui/icons-material/ChevronRight';
import TreeItem, { treeItemClasses } from '@mui/lab/TreeItem';

import { motion, useAnimation } from "framer-motion"
import { useInView } from "react-intersection-observer";
import { useEffect, Fragment } from "react";

const NoteItem = ({ children, title, mainIcon }) => (
  <>
      <Tooltip content={children} color="primary" style={{paddingLeft: ".3rem"}}>
        <div className="svgContainer">{mainIcon}</div>
      </Tooltip>
  </>
)
  

const ProjectTitle = ({ children, notes }) => (
  <div
  className={stylesProject.hFlex}>
      <Text weight="medium" className={stylesProject.projectTitle}>
        {children}
      </Text>
    <div className="noteContainer" style={{ flex: "1", display: "inline-block"}}>
      {notes.map((item,index)=>(
        <NoteItem key={item.title + index} mainIcon={item.displayIcon} title={item.title}>{item.description}</NoteItem>
      ))}
    </div>
  </div>
)

const ProjectItem = ({ title, children, notes=[], links=[] }) => (
  <div className={stylesProject.projectItem}>
    <ProjectTitle key={title} notes={notes}>{title}</ProjectTitle>
    {children}
    <div className={stylesProject.hFlex}>
      {
      links.map((item,index)=>(
        <Fragment key={item.title + toString(index)}>
          <Link href={item.url} rel="noreferrer" target="_blank">
            <Button style={{height: '1.4rem', marginTop: ".4rem", fontSize: "0.8rem"}}
              auto rounded bordered
              >
                {item.title}
            </Button>
          </Link>
          <Spacer x={0.5}/>
        </Fragment>
      ))
      }
    </div>
  </div>
)


const ProjectItemCollapse = ({title, children, notes, links }) => {

  const control = useAnimation();
  const [ref, inView] = useInView();

  useEffect(() => {
    if (inView) {
      control.start("visible");
    } else {
      control.start("hidden");
    }
  }, [control, inView]);

  return <LazyShow
      >
        <Collapse
          title={
            <ProjectItem
              key={title}
              title={title}
              notes={notes}
              links={links}>
            </ProjectItem>
          }
          shadow={true}
          bordered={true}
          >
          <Text>
            {children}
          </Text>
        </Collapse>
      </LazyShow>
  
}









export default function Projects() {
  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/websiteicon.ico" />
      </Head>
      <div>
        <h2>Research</h2>
        <p className={stylesProject.projectSectionCaption}>
          For any substantial ongoing or completed research work, please see below. 
          The availability of certain code repositories or papers may depend on the project&apos;s current status (e.g., 
           the links associated with any project in the process of publication may be temporarily unavailble).
        </p>
        <Grid.Container gap={0}>
          <Grid>
            <Collapse.Group splitted css={{padding: 0}}>
              <ProjectItemCollapse 
                title="Private Access Control for Function Secret Sharing" 
                links={[{title: "Paper"}, {title: "Github"}]}>
                  Written in conjunction with MIT PRIMES. Cryptography paper developing distributed zero knowledge proof protocols towards access control for secret-shared functions.
              </ProjectItemCollapse> 


              <ProjectItemCollapse title="Cloak: A Versatile Framework for Anonymous Authentication" 
              links={[{title: "Paper"}, {title: "Github"}]}
              >
                Written in conjunction with MIT PRIMES. Cryptography paper developing privacy preserving authentication through secret-shared zero-knowledge proof protocols.
              </ProjectItemCollapse>

              <ProjectItemCollapse title="Authenticated Metadata-hiding Anonymous Communication" 
              links={[{title: "Paper"}, {title: "Github"}]}
              >
                Independent research paper exploring how anonymous authentication techniques can be used to improve the current state of the art in anonymous communication systems with cryptographic privacy guarantees. 
              </ProjectItemCollapse>

              <ProjectItemCollapse title="Seed-Homomorphic Pseudorandom Generators from Learning with Errors / Multi-Server Distributed Point Functions" 
              links={[]}
              >
                (Still in the works!)
              </ProjectItemCollapse>

              <ProjectItemCollapse title="Moderately Hard Functions" 
              links={[]}
              >
                (Still in the works!)
              </ProjectItemCollapse>   
                
            </Collapse.Group>
          </Grid>
        </Grid.Container>
        
        
      </div>
      <div>
      <h2>Other cool projects</h2>
      <p className={stylesProject.projectSectionCaption}>
          For any other interesting past projects or code resources, see below. 
        </p>
      <Grid.Container>
          <Grid>
            <Collapse.Group splitted css={{padding: 0}}>
            <ProjectItemCollapse title="SigmaML" 
            links={[{title: "Github", url: "https://github.com/sim15/sigmaml"}]}
            >
              A cross-platform desktop application for building machine learning models, aggregating all steps of the development process. Built with web-based technology: JavaScript, Svelte, Electron, Python.
            </ProjectItemCollapse>
            <ProjectItemCollapse title="Mealgo: Recipe Filtering" 
            links={[{title: "Poster", url: "/a4g_mealgo_poster.pdf"}, {title: "Github", url: "https://github.com/sim15/Mealgo3"}]}
            >
              Android application designed to provide intelligent meal and recipe recommendation that considers both pricing and individual user preferences. Developed with a tailored dataset of over 500,000 recipes and thousands of unique ingredients, all with their respective nutritional information. Developed in Kotlin.
            </ProjectItemCollapse>
            <ProjectItemCollapse title="NaVi: Aid for Independent Navigation for the Visually Impaired" 
            links={[{title: "Poster", url: "/navi_poster.pdf"}]}
            >
              Designed a physical aid for the independent navigation of public spaces for those with visual impairments. Designed software for automated guidance and designed a haptic device to aid those attempting to navigate through unadapted environments. Allows for independent parties to deploy schematics that aid individuals in the respective space.
            </ProjectItemCollapse>
            <ProjectItemCollapse title="IMMC 2022" 
            notes={[{displayIcon: <Award/>, title: "", description: "Awarded US Finalist"}]}
            links={[]}>
              Mathematical modeling paper written during a the 2022 International Mathematical Modeling Competition (IMMC). 
              Modeled planar loading and disembarking while optimizing both processes in a diverse set of aircrafts.
            </ProjectItemCollapse>
            <ProjectItemCollapse title="HiMCM 2021" 
            notes={[{displayIcon: <Award/>, title: "", description: "Awarded Meritorious"}]}
            links={[{title: "Paper"}]}>
              Mathematical modeling paper written during the 2021-22 High School Mathematical Contest in Modeling (HiMCM).
              Modeled the causes, future outlook, and potential consequences of rapidly depleting water levels at Lake Mead, Nevada, the nations largest freshwater reservoir.
            </ProjectItemCollapse>
            <ProjectItemCollapse title="MathWorks 2022" 
            notes={[{displayIcon: <Award/>, title: "", description: "Advanced to Second Round of Competition (Top ~100 papers)"}]}
            links={[{title: "Paper"}]}>
               Mathematical modeling paper written during the 2022 MathWorks Mathematical Modeling Competition. 
                Modeled changes in employment caused by a pandemic-induced virtual workplace. Considered future outlook, causes, and conducted a broader mathematical and social analysis.
            </ProjectItemCollapse>  
                
            </Collapse.Group>
          </Grid>
        </Grid.Container>
      </div>

      <div>
      <h2>Mass Academy Coursework</h2>
      <p className={stylesProject.projectSectionCaption}>
          For prospective Mass Academy students, alumni, or for anyone interested: past assignments and projects completed 
          during the 2021-22 school year are available upon request. Certain assignments will be available in the future.
        </p>
        {/* <TreeView
          aria-label="file system navigator"
          defaultCollapseIcon={<ExpandMoreIcon />}
          defaultExpandIcon={<ChevronRightIcon />}
          sx={{ height: 440, flexGrow: 1, overflowY: 'auto' }}
        >
          <TreeItem nodeId="1" label="Mathematics">
            <TreeItem nodeId="2" label="Calendar" />
          </TreeItem>
          <TreeItem nodeId="3" label="Computer Science">
            <TreeItem nodeId="4" label="Calendar" />
          </TreeItem>
          <TreeItem nodeId="5" label="Humanities">
            <TreeItem nodeId="6" label="Essays" />
            <TreeItem nodeId="13" label="Presentations/Misc." >
              <TreeItem
              label="Satire Video"/>
            </TreeItem>
          </TreeItem>
          <TreeItem nodeId="7" label="Physics">
            <TreeItem nodeId="8" label="Calendar" />
          </TreeItem>
          <TreeItem nodeId="9" label="Spanish">
            <TreeItem nodeId="10" label="Calendar" />
          </TreeItem>
          <TreeItem nodeId="11" label="STEM">
            <TreeItem nodeId="12" label="Calendar" />
          </TreeItem>
      </TreeView> */}
      </div>
    </>
  )
}
